project:
  type: website

website:
  title: "Sofia Jain"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: Courses.qmd
        text: Courses
  page-footer: 
    right: "&copy; 2024, Sofia Jain"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto

editor: visual

